name: ðŸ’¬ Notify
on:
  workflow_call:
    inputs:
      environment-name:
        type: string
        required: true
    secrets:
      webhook-url:
        required: true
jobs:
  slack_notification:
    name: ðŸ’¬ Slack notification
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        id: slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "ðŸš€ New version deployed",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "ðŸš€ ${{ vars.RADIX_APPLICATION_NAME }} - Deployed new version to ${{ inputs.environment-name }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.webhook-url }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
